apiVersion: v1
kind: Service
metadata:
  name: controller-manager-metrics-service
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    kubevirt.io: virt-template-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: virt-template
