apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apiserver-auth-reader
  namespace: kube-system
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    kubevirt.io: virt-template-apiserver-auth-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: virt-template-apiserver
    namespace: kubevirt
