apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiserver-rolebinding
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    kubevirt.io: virt-template-apiserver-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apiserver-role
subjects:
- kind: ServiceAccount
  name: apiserver
  namespace: system
