apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiserver
  namespace: system
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    kubevirt.io: virt-template-apiserver
