# This rule is not used by the project virt-template itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the template.kubevirt.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinetemplate-editor-role
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    kubevirt.io: virt-template-virtualmachinetemplate-editor-role
rules:
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplates
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplates/status
  verbs:
  - get
