# This rule is not used by the project virt-template itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over template.kubevirt.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinetemplaterequest-admin-role
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    kubevirt.io: virt-template-virtualmachinetemplaterequest-admin-role
rules:
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplaterequests
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplaterequests/status
  verbs:
  - get
