# This rule is not used by the project virt-template itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to use VirtualMachines in a namespace as source
# for VirtualMachineTemplateRequests.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinetemplaterequest-source-role
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    kubevirt.io: virt-template-virtualmachinetemplaterequest-source-role
rules:
- apiGroups:
  - template.kubevirt.io
  resources:
  - virtualmachinetemplaterequests/source
  verbs:
  - create
