apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.subresources.template.kubevirt.io
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    kubevirt.io: virt-template-apiserver-aggregator
spec:
  group: subresources.template.kubevirt.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: virt-template-api-service
    namespace: system
  version: v1alpha1
