apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiserver.yaml
- apiservice.yaml
- service.yaml
images:
- name: apiserver
  newName: quay.io/kubevirt/virt-template-apiserver
  newTag: latest
