apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: system
  labels:
    app.kubernetes.io/name: virt-template
    app.kubernetes.io/managed-by: kustomize
    kubevirt.io: virt-template-api-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: apiserver
    app.kubernetes.io/name: virt-template
