## Append samples of your project ##
resources:
- template_v1alpha1_virtualmachinetemplate.yaml
- template_v1alpha1_virtualmachinetemplaterequest.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
